cmd_drivers/misc/mediatek/video/common/data_rgb888_64x64.o := arm-eabi-gcc -Wp,-MD,drivers/misc/mediatek/video/common/.data_rgb888_64x64.o.d  -nostdinc -isystem /home/kirito9/android/toolchain/arm-eabi-4.8/bin/../lib/gcc/arm-eabi/4.8/include -I./arch/arm/include -Iarch/arm/include/generated  -Iinclude -I./arch/arm/include/uapi -Iarch/arm/include/generated/uapi -I./include/uapi -Iinclude/generated/uapi -include ./include/linux/kconfig.h -D__KERNEL__ -mlittle-endian -Iarch/arm/mach-mediatek/include -I./drivers/misc/mediatek/include/mt-plat/mt6580/include -I./arch/arm/mach-mediatek/include/ -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -std=gnu89 -fno-dwarf2-cfi-asm -fno-omit-frame-pointer -mapcs -mno-sched-prolog -mabi=aapcs-linux -mno-thumb-interwork -mfpu=vfp -marm -D__LINUX_ARM_ARCH__=7 -march=armv7-a -msoft-float -Uarm -fno-delete-null-pointer-checks -O2 --param=allow-store-data-races=0 -Werror=frame-larger-than=1 -Wframe-larger-than=1400 -fno-stack-protector -Wno-unused-but-set-variable -fno-omit-frame-pointer -fno-optimize-sibling-calls -fno-var-tracking-assignments -g -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fconserve-stack -Werror=implicit-int -Werror=strict-prototypes -DCC_HAVE_ASM_GOTO -Werror -I./drivers/misc/mediatek/hibcore -I./drivers/misc/mediatek/include -I./drivers/misc/mediatek/include/mt-plat/mt6580/include -I./drivers/misc/mediatek/include/mt-plat -I./drivers/mmc/host/mediatek/mt6580 -I./drivers/misc/mediatek/mmp/ -I./drivers/misc/mediatek/m4u/mt6580 -I./drivers/misc/mediatek/m4u/mt6580/mt6735 -I./drivers/misc/mediatek/video/include -I./drivers/misc/mediatek/video/common/IPv1 -I./drivers/misc/mediatek/video/mt6580/dispsys -I./drivers/misc/mediatek/video/mt6580/videox -I./drivers/misc/mediatek/sync/ -I./drivers/misc/mediatek/cmdq/v2/ -I./drivers/misc/mediatek/cmdq/v2/mt6580/ -I./drivers/misc/mediatek/lcm/inc -I./drivers/staging/android/ion -I./drivers/staging/android/ion/mtk    -D"KBUILD_STR(s)=\#s" -D"KBUILD_BASENAME=KBUILD_STR(data_rgb888_64x64)"  -D"KBUILD_MODNAME=KBUILD_STR(data_rgb888_64x64)" -c -o drivers/misc/mediatek/video/common/data_rgb888_64x64.o drivers/misc/mediatek/video/common/data_rgb888_64x64.c

source_drivers/misc/mediatek/video/common/data_rgb888_64x64.o := drivers/misc/mediatek/video/common/data_rgb888_64x64.c

deps_drivers/misc/mediatek/video/common/data_rgb888_64x64.o := \

drivers/misc/mediatek/video/common/data_rgb888_64x64.o: $(deps_drivers/misc/mediatek/video/common/data_rgb888_64x64.o)

$(deps_drivers/misc/mediatek/video/common/data_rgb888_64x64.o):
